name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '8'
          cache: 'maven'
      - name: maven-settings-xml-action
        uses: whelk-io/maven-settings-xml-action@v21
        with:
            repositories: >
             [
              {
              "id": "pentaho-public",
              "name": "Pentaho Public",
              "url": "https://repo.orl.eng.hitachivantara.com/artifactory/pnt-mvn/",
              "releases": {
                  "enabled": "true",
                  "updatePolicy": "always"
              },
             "snapshots": {
              "enabled": "true",
              "updatePolicy": "always"
             }
             }
             ]
            plugin_repositories: >
             [
             {
             "id": "pentaho-public",
             "name": "Pentaho Public",
             "url": "https://repo.orl.eng.hitachivantara.com/artifactory/pnt-mvn/",
             "releases": {
               "enabled": "true",
               "updatePolicy": "always"
               },
             "snapshots": {
              "enabled": "true",
              "updatePolicy": "always"
              }
             }
             ]
             servers: >
             [
             {
             "id": "pentaho-public",
             "username": "devreaduser",
             "password": "piMs58wRfyyZbEM"
             }
             ]
            output_file: .m2/settings.xml
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
